name: Python application

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test with pytest
        run: python3 test_file.py

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_URL }}
          subject: "subject: GitHub Actions job result"
          to: souravmalani95@example.com # Required recipient's address
          from: Ahsan Qamar <qaahsan92@gmail.com> # Required sender full name and address
          body: Build job of ${{github.repository}} completed successfully!
